apiVersion: "marketplace.redhat.com/v1alpha1"
kind: "CatalogSourceConfig"
metadata:
  name: "installed-upstream-community-operators"
  namespace: "marketplace"
spec:
  targetNamespace: local-operators
  packages: jaeger

