kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: marketplace-operator
rules:
- apiGroups:
  - marketplace.redhat.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - operators.coreos.com
  resources:
  - catalogsources
  verbs:
  - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-marketplace-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: marketplace
roleRef:
  kind: ClusterRole
  name: marketplace-operator
  apiGroup: rbac.authorization.k8s.io
